### ISSUE TITLE
:bug: Incompatibility with seaborn

### ISSUE THREAD

**Issue by o-laurent** [aperezlebel/glest#4]
Hello! 

Thank you so much for your amazing work! Would it be possible to change the name of the colormap "flare" that you define in your lib? I have indeed the following bug:

```python
>>> import seaborn as sns
>>> from glest import GLEstimator
```

that results in 
```text
ValueError: A colormap named "flare" is already registered.
```

Thanks in advance!

PS: Switching the two lines is a simple workaround, but I thought that you may be interested to solve this potential issue for users. Furthermore, it could be a problem for libraries building on top of yours such as [ours](https://github.com/ENSTA-U2IS/torch-uncertainty).

**Comment by aperezlebel** [comment]
Thank you for pointing this out! I'm adding it to the to-do list.

**Comment by o-laurent** [comment]
Hey @aperezlebel, 

This is now a major concern as we need to add seaborn in our dependencies. Can you solve this problem in the following days? If not, we will internalize the part of your code we need with a citation to your repository.

Have a great day!

**Comment by aperezlebel** [comment]
Hey, thanks for the reminder. Fixing this asap.

**Comment by aperezlebel** [comment]
@o-laurent Could you confirm that #6 fixes the issue?

**Comment by o-laurent** [comment]
Thank you! It seems to be working. Will you make a small release with this fix?

**Comment by aperezlebel** [comment]
Done! It is v0.0.1a1.

**Comment by o-laurent** [comment]
Many thanks! We'll update our pyproject.toml!
